# Test configuration for npm project
severity:
  major: error
  minor: warning
  patch: info

output:
  format: sarif
  file: npm-report.sarif

# Ignore the non-existent package since we know it's just for testing
ignorePackages:
  - nonexistent-npm-package-for-test
