# Test configuration for Python/Pip project
severity:
  major: error
  minor: warning
  patch: info

output:
  format: json
  file: pip-report.json

# Ignore the non-existent package since we know it's just for testing
ignorePackages:
  - nonexistent-package-for-test
